# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Import Certificates and Provisioning Profile"
  private_lane :import_certificates_and_provisioning_profile do
    create_keychain(
        name: "mykeychain",
        password: ENV["KEYCHAIN_PASSWORD"],
        timeout: 1000
    )
    import_certificate(
        certificate_path: "certificates.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "mykeychain",
        keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    install_provisioning_profile(path: "ios.mobileprovision")
  end

  desc "Deploy Debug App to App Store"
  lane :deploy_debug do

    cocoapods

    import_certificates_and_provisioning_profile

    increment_build_number

    commit_version_bump(
        message: "update build version",
        xcodeproj: "./github-action.xcodeproj"
    )

    gym(workspace: "github-action.xcworkspace",
        scheme: "Debug",
        clean: true,
        export_options: {
            method: "ad-hoc"
        }
    )

    delete_keychain(name: "mykeychain")
  end
end
