name: Deploy Staging App

on:
  push:
    branches: [ deploy/staging ]

jobs:
  build:
    name: Deploy Staging App to App Store
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Xcode Path
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app/Contents/Developer

    - name: Import Certificates and Provisioning Profile
      run: |
        echo "${{ secrets.CERTIFICATES_P12 }}" > certificates.p12.txt
        base64 --decode certificates.p12.txt > certificates.p12
        echo "${{ secrets.PROVISIONING_PROFILE }}" > ios.mobileprovision.txt
        base64 --decode ios.mobileprovision.txt > ios.mobileprovision

    - name: Bundle Install
      run: bundle install

    - name: Upload App Store
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      run: bundle exec fastlane deploy_staging

    - name: Increment Build Number
      run: bundle exec fastlane add_build_number

    - name: Rebase Release
      run: |
        git config --local user.email "runner@${{ runner.os }}"
        git config --local user.name "runner"
        git fetch
        git log --pretty="%h" deploy/staging | head -n 1
        hash=$(git log --pretty="%h" deploy/staging | head -n 1)
        echo $(git branch --contains $hash | grep "release/") | sed 's/\*\ //g'
        branch_name=$(git branch --contains $hash | grep "release/") | sed 's/\*\ //g'
        echo $branch_name
        git checkout $branch_name
        git rebase deploy/staging
        git push