name: Test Workflow

on:
  push:
    branches: [ feature/test ]

jobs:
  build:
    name: Test
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Git fetch
      run: |
        git config --local user.email "runner@${{ runner.os }}"
        git config --local user.name "runner"
        git fetch --all
        git log --all --pretty="%h %d %s %an"
